=== luciadelagranda/SEW/XML/UO251626-entrega2/p2/Ejercicio 2/Tarea 3/Recetas.dtd
<!ELEMENT recetas (receta*)>
<!ELEMENT receta (nombre,tipo,ingredientes*,calorias,pasos*,dificultad,tiempo,elementos*,origen)>

<!ELEMENT ingredientes (ingrediente*)>
<!ELEMENT pasos (paso*)>
<!ELEMENT elementos (elemento*)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT elemento (#PCDATA)>
<!ELEMENT dificultad (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT paso (#PCDATA)>
<!ELEMENT calorias (#PCDATA)>

<!ATTLIST tipo plato CDATA #REQUIRED>
<!ATTLIST ingrediente nombre CDATA #REQUIRED>
<!ATTLIST ingrediente cantidad CDATA #REQUIRED>
<!ATTLIST ingrediente nombre CDATA #REQUIRED>
<!ATTLIST ingrediente medida CDATA #REQUIRED>
<!ATTLIST paso numero CDATA #REQUIRED>
<!ATTLIST paso descripcion CDATA #REQUIRED>
<!ATTLIST dificultad grado CDATA #REQUIRED>
<!ATTLIST tiempo minutos CDATA #REQUIRED>
<!ATTLIST elemento nombre CDATA #REQUIRED>
<!ATTLIST calorias  kcal CDATA #REQUIRED>

=== luciadelagranda/SEW/XML/Ejercicios/p4/Ejercicio 2/Tarea 1/Recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="Recetas.css"?>
<?xml-stylesheet type="text/xsl" href="Recetas.xsl"?>
<!DOCTYPE recetas SYSTEM "Recetas.dtd">
<recetas>
	<receta>
		<nombre>Palmeritas de hojaldre</nombre>
		<tipo plato="Postre"/>
        <ingredientes>
		<ingrediente nombre="lamina hojaldre" cantidad="1" medida="lamina"/>
		<ingrediente nombre="azúcar normal" cantidad="200" medida="g"/>
        </ingredientes>
		<calorias kcal="200"/>
        <pasos>
			<paso numero="1" descripcion="Poner azúcar sobre una mesa plana y estirar sibre el la lámina de hojaldre"/>
			<paso numero="2" descripcion="Estirar con un rodillo, sin hacer mucha fuerza, la lamina de hojaldre y echar más azúcar"/>
			<paso numero="3" descripcion="Doblar y volver a echar más azúcar"/>
			<paso numero="4" descripcion="Cortar en trozos no más grandes de 1 cm y poner a precalentar el horno a 210º"/>
			<paso numero="5" descripcion="Meter las palmeras en el horno durante 20 min ,aproximadamente, dejando el espacio suficiente para que crezcan y colocandolas sobre un papel de hornear"/>
        </pasos>
		<dificultad grado="1"/>
		<tiempo minutos="30"/>
        <elementos>
			<elemento nombre="horno"/>
			<elemento nombre="rodillo de masa"/>
        </elementos>
		<origen>Agenda de Mr.Wonderful</origen>
	</receta>
	<receta>
		<nombre>Pollo Satay</nombre>
		<tipo plato="Entrante"/>
        <ingredientes>
		<ingrediente nombre="Pollo" cantidad="1 " medida="kg"/>
		<ingrediente nombre="Leche" cantidad="400" medida="ml"/>
		<ingrediente nombre="curry en polvo" cantidad="1" medida="cucharada"/>
		<ingrediente nombre="cúrcuma en polvo" cantidad="1" medida="cuharada"/>
		<ingrediente nombre="semillas de cilantro" cantidad="1/2" medida="cuharada"/>
		<ingrediente nombre="semillas de comino" cantidad="1/2" medida="cuharada"/>
		<ingrediente nombre="sal" cantidad="1" medida="cuharadita"/>
        </ingredientes>
		<calorias kcal="45"/>
        <pasos>
			<paso numero="1" descripcion="En una sartén tostamos el cilantro y el comino, cuando empiece a oler bien lo pasamos a un mortero y lo machacamos bien hasta conseguir un polvo fino. Reservamos para luego."/>
			<paso numero="2" descripcion="Cortamos el pollo en trocitos finos y lo ponemos en un bol."/>
			<paso numero="3" descripcion="Le añadimos el cilantro y comino en polvo, el curry, la cúrcuma, la sal, la pimienta blanca y la leche en polvo. Lo mezclamos todo bien, lo tapamos y dejamos marinar en la nevera durante al menos 2 horas o mejor toda la noche."/>
			<paso numero="4" descripcion="Lo sacamos y hacemos nuestros pinchitos, colocando unos cuantos trocitos de pollo por pinchito."/>
			<paso numero="5" descripcion="Y ya está listo para la plancha, lo cocinamos bien por ámbos lados y ya está listo para servir acompañado de su salsa Satay."/>
        </pasos>
		<dificultad grado="2"/>
		<tiempo minutos="240"/>
        <elementos>
			<elemento nombre="sartén"/>
			<elemento nombre="mortero"/>
			<elemento nombre="bol"/>
			<elemento nombre="pinchos de madera"/>
        </elementos>
		<origen>http://www.kwanhomsai.com/pollo-satay-estilo-thai/</origen>
	</receta>
	<receta>
		<nombre>Salsa Satay</nombre>
		<tipo plato="Acompañante"/>
        <ingredientes>
		<ingrediente nombre="pasta de tamarindo" cantidad="3" medida="cucharada"/>
		<ingrediente nombre="Leche" cantidad="400" medida="ml"/>
		<ingrediente nombre="curry Massaman" cantidad="2" medida="cucharada"/>
		<ingrediente nombre="azúcar de palma" cantidad="100" medida="g"/>
		<ingrediente nombre="cacahuetes tostados machacados" cantidad="50" medida="g"/>
		<ingrediente nombre="sal" cantidad="1/2" medida="cucharadita"/>
        </ingredientes>
		<calorias kcal="40"/>
        <pasos>
			<paso numero="1" descripcion="En un cazo calentamos 1/4 de la leche de coco y la pasta de curry sin dejar de remover hasta que salga su aceite."/>
			<paso numero="2" descripcion="Añadimos el resto de la leche de coco, los cacahuetes tostados, la pasta de tamarindo, el azúcar de palma y la salsa de pescado si es necesario."/>
			<paso numero="3" descripcion="Cocinamos un par de minutos hasta que todo quede bien incorporado y ya está lista para acompañar al pollo Satay."/>
        </pasos>
		<dificultad grado="1"/>
		<tiempo minutos="20"/>
        <elementos>
			<elemento nombre="sartén"/>
			<elemento nombre="bol"/>
        </elementos>
		<origen>http://www.kwanhomsai.com/salsa-satay-estilo-thai/</origen>
	</receta>
	<receta>
		<nombre>Hamburgesa vegana de garbanzo y calabacín</nombre>
		<tipo plato="Segundo"/>
        <ingredientes>
		<ingrediente nombre="garbanzos cocidos" cantidad="300" medida="g"/>
		<ingrediente nombre="calabacín grande" cantidad="1/4" medida="pieza"/>
		<ingrediente nombre="semillas de lino molidas" cantidad="3" medida="cucharada"/>
		<ingrediente nombre="curry" cantidad="1" medida="cucharada"/>
		<ingrediente nombre="sal" cantidad="1" medida="cucharada"/>
        </ingredientes>
        <calorias kcal="40"/>
        <pasos>
			<paso numero="1" descripcion="Deberemos triturar los garbanzos y salarlos al gusto"/>
			<paso numero="2" descripcion="Lavamos el calabacín y trituramos también. Mezclamos y añadimos curry al gusto. "/>
			<paso numero="3" descripcion=" Amasamos y vamos añadiendo poco a poco las semillas de lino molidas y la harina."/>
			<paso numero="4" descripcion="Cuando tengamos una masa homogénea separamos en bolas y después aplastamos las formar las hamburguesas veganas."/>
			<paso numero="5" descripcion="Después podemos freír o bien reservar en la nevera o congelador. Yo siempre lo hago envolviendo de manera individual las hamburguesas en film transparente."/>
		</pasos>
        <dificultad grado="2"/>
		<tiempo minutos="20"/>
        <elementos>
			<elemento nombre="sartén"/>
			<elemento nombre="bol"/>
		</elementos>
        <origen>http://beginveganbegun.es/2015/11/28/hamburguesas-veganas-de-garbanzo-y-lentejas/</origen>
	</receta>
	<receta>
		<nombre>Tarta de judías y calabaza</nombre>
		<tipo plato="Postre"/>
        <ingredientes>
		<ingrediente nombre="Judías" cantidad="2" medida="taza"/>
		<ingrediente nombre="Arroz integral" cantidad="2" medida="taza"/>
		<ingrediente nombre="Calabaza" cantidad="1/2" medida="kg"/>
		<ingrediente nombre="Pimiento rojo" cantidad="1" medida="pieza"/>
		<ingrediente nombre="Cebolla" cantidad="1" medida="pieza"/>
		<ingrediente nombre="Ajo" cantidad="1" medida="pieza"/>
		<ingrediente nombre="Perejil" cantidad="1" medida="pieza"/>
		<ingrediente nombre="Oregano" cantidad="1" medida="cucharadita"/>
		<ingrediente nombre="Aceite de oliva" cantidad="10" medida="ml"/>
		<ingrediente nombre="Sal" cantidad="1" medida="cucharadita"/>
        </ingredientes>
        <calorias kcal="89"/>
        <pasos>
			<paso numero="1" descripcion="Primero trituramos las judías aún calientes después de haberlas cocido y colocamos en un bol."/>
			<paso numero="2" descripcion="Aparte mezclamos el arroz también cocido y caliente, el ajo y el perejil picados. Mezclar bien, condimentando con la sal y el orégano."/>
			<paso numero="3" descripcion="Extender con las manos en un molde aceitado, dejando un borde alrededor para contener el relleno. Hornear a temperatura alta unos 10 minutos. Retirar y servir con una guarnición de vegetales crudos."/>
			<paso numero="4" descripcion="Aparte untar una cacerola con el aceite y colocar adentro la cebolla, el pimiento rojo y la calabaza cortada en trocitos pequeños. Tapar y cocinar a fuego suave unos 10 minutos. Retirar e incorporar las judías cocidas del bol y procesadas."/>
			<paso numero="5" descripcion="Condimentar, mezclar bien y verter sobre la masa base. Dejr reposar y a disfrutar de la tarta de judías y calabaza."/>
		</pasos>
        <dificultad grado="3"/>
		<tiempo minutos="160"/>
        <elementos>
			<elemento nombre="sartén"/>
			<elemento nombre="bol"/>
        </elementos>
		<origen>https://paravegetarianos.com/recetas-vegetarianas/tarta-de-judias-y-calabaza_rv1234</origen>
	</receta>
	<receta>
		<nombre>Cuajada</nombre>
		<tipo plato="Postre"/>
        <ingredientes>
		<ingrediente nombre="Leche" cantidad="1/2" medida="l"/>
		<ingrediente nombre="Azúcar" cantidad="2" medida="cucharada"/>
		<ingrediente nombre="Gotas Cuajo" cantidad="1" medida="pieza"/>
		<ingrediente nombre="Hojas de menta" cantidad="2" medida="pieza"/>
        </ingredientes>
		<calorias kcal="200"/>
        <pasos>
			<paso numero="1" descripcion="Calienta la leche en una cazuela. Deja que se temple a 37ºC ."/>
			<paso numero="2" descripcion="Vierte un par de gotas de cuajo en cada cuenco y añade la leche."/>
			<paso numero="3" descripcion="Deja que cuaje sin mover los recipientes."/>
        </pasos>
		<dificultad grado="1"/>
		<tiempo minutos="20 "/>
        <elementos>
			<elemento nombre="bol"/>
			<elemento nombre="cacuela"/>
        </elementos><origen>https://www.hogarmania.com/cocina/recetas/postres/201108/cuajada-9646.html</origen>
	</receta>
	<receta>
		<nombre>Tortilla de patatas</nombre>
		<tipo plato="Principal"/>
        <ingredientes>
		<ingrediente nombre="Huevo" cantidad="6" medida="pieza"/>
		<ingrediente nombre="Patatas" cantidad="600" medida="g"/>
		<ingrediente nombre="Cebolla" cantidad="1" medida="pieza"/>
		<ingrediente nombre="Pimiento Verde" cantidad="1" medida="pieza"/>
		<ingrediente nombre="Aceite oliva" cantidad="2" medida="vasos"/>
		<ingrediente nombre="Sal" cantidad="1" medida="cuharadita"/>
		<ingrediente nombre="Hoja perejil" cantidad="1" medida="pieza"/>
        </ingredientes>
		<calorias kcal="129"/>
        <pasos>
			<paso numero="1" descripcion="Pela y pica la cebolla en dados medianos."/>
			<paso numero="2" descripcion="Limpia el pimiento verde, retírale el tallo y las pepitas y córtalo en dados."/>
			<paso numero="3" descripcion="Si las patatas estuvieran sucias, pásalas por agua. Pélalas, córtalas por la mitad a lo largo y después corta cada trozo en medias lunas finas de 1/2 centímetros."/>
